# Generated by Django 5.0.3 on 2024-03-12 11:23

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_image_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='more_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
