# Generated by Django 5.0.2 on 2024-02-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_categorie_category_alter_blogcomment_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
